### ISSUE TITLE
requireNativeComonent: "RNSScreen" was not found in the UIManager

### ISSUE THREAD

**Issue by Kilros0817** [invertase/react-native-firebase-authentication-example#13]
I have run this command "npx react-native init react_native_firebase_authenticatioin_project --template invertase/react-native-firebase-authentication-example"
and npm run android
But I faced following errors

![Screenshot_1665579722](https://user-images.githubusercontent.com/96753457/195350566-04454143-b85a-4a6d-9cca-c29e1d34a466.png)

 LOG  Running "react_native_firebase_authenticatio_project" with {"rootTag":21}
 ERROR  Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.

This error is located at:
    in RNSScreen (created by AnimatedComponent)
    in AnimatedComponent
    in AnimatedComponentWrapper (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RNGestureHandlerRootView (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by SignedOutStack)
    in SignedOutStack (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in AlertsProvider (created by App)
    in ThemeProvider (created by Provider)
    in RCTView (created by View)
    in View (created by Portal.Host)
    in Portal.Host (created by Provider)
    in Provider (created by App)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by App)
    in App
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in react_native_firebase_authenticatio_project(RootComponent), js engine: hermes
 WARN  Possible Unhandled Promise Rejection (id: 0):
Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.
Invariant Violation: requireNativeComponent: "RNSScreen" was not found in the UIManager.
   

Please help me to solve this issue

**Comment by mikehardy** [comment]
https://stackoverflow.com/a/74045159/9910298

You need to pin react-native-screens to *exactly* 3.13.0 version, 3.13.1 includes an invalid configuration for older react-native versions

There is very limited support for this example - apologies - and I do not have time to update it frequently, so the dependencies inside are a bit stale. An alternative solution is to update react-native inside the created app to react-native 0.70.3 (current stable) then it will also work

**Comment by Kilros0817** [comment]
Hi! mikehardy
I have solved issue. Current react-native-screens viersion is the latest 3.18.1 which is published yesterday. And has the unallowed "dependency.platforms.android.componentDescriptors" so react-native-screens are ignored from react-native
So I have downgrade it's version to 3.17.0
Then works well
Thanks again
