### ISSUE TITLE
[auth/invalid-credential] The supplied auth credential is malformed or has expired.

### ISSUE THREAD

**Issue by raahimkhan** [invertase/react-native-firebase-authentication-example#16]
I configured Google login in my React Native app for both Android and iOS using the package: `@react-native-google-signin/google-signin`.

It is working perfectly fine.

Next, I decided to add Firebase auth to my project. I added Firebase auth and enabled Google as the auth provider in Firebase console. It is working perfectly fine on Android but on iOS I keep getting the error: `[auth/invalid-credential] The supplied auth credential is malformed or has expired.`

There is not much on the web/Google regarding this error. Whatever resolutions were there I already tried those. Right now getting really frustrated with this error. Can anyone please help what might be causing this? Here is my relevant code snippet which is working fine for Android:

```javascript
const firebaseGoogleLogin = async () => {
        try {
            if (Platform.OS === 'android') {
                const status = await GoogleSignin.hasPlayServices();
                if (!status) {
                    Alert.alert('Google Play Services not installed or enabled. Please install or enable Google Play Services');
                    return;
                }
            }
            await GoogleSignin.signOut();
            const userInfo = await GoogleSignin.signIn();
            if (userInfo.data) {
                const tokens = await GoogleSignin.getTokens();
                const credential = auth.GoogleAuthProvider.credential(
                    tokens.idToken,
                    tokens.accessToken
                );
                await auth().signInWithCredential(credential);
            }
        }
        catch (error: any) {
            Alert.alert('Some error happened during Google login', error.message);
        }
    }
```

I have double checked the bundleID on firbase console, google cloud console, app.json as well. They are exactly the same. Client ID and reversed client id are also present in `GoogleService-Info.plist` file. I am also using the updated and most recently generated `GoogleService-Info.plist` from Firebase console as well.

Please can anyone help me resolve this error. Happening on iOS only.

**Comment by mikehardy** [comment]
Maybe this https://github.com/invertase/react-native-firebase/commit/43ebcde644f9e582f4ec2d6a2bcedfa2b2e42956

But this issue report is missing all sorts of vital information like versions etc:
https://stackoverflow.com/help/how-to-ask

Most importantly though, we don't offer support for project-specific type issues in this repo:

https://github.com/invertase/react-native-firebase-authentication-example/blob/68bd37f8c219f892655b40c73e9818370f368b82/README.md?plain=1#L11

**Comment by mikehardy** [comment]
@raahimkhan thanks so much for your understanding of my priorities and time constraints, it is greatly appreciated

https://medium.com/hackernoon/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b
