### ISSUE TITLE
first installation problem

### ISSUE THREAD

**Issue by mtalhagaoglu** [invertase/react-native-firebase-authentication-example#8]
hi,

i have a weird problem.

after I create a project with the command 
`npx react-native init ProjectName --template invertase/react-native-firebase-authentication-example`
 I can't start the project. `npm install` or `yarn` does not create node_modules. when I tried a blank project it is all okey but with the template it does not work.

do you guys have any idea what it causes?

**Comment by mikehardy** [comment]
Hi there! No I'm sorry, I have no idea what could be going wrong. 
I run the command you specified (by copy/paste) and then after `cd ProjectName` running `yarn` works fine. In fact simply after doing the init, node_modules already exists, as the init takes care of that and the pod install the first time.
I suspect you  never switched into the project directory
